site_name: pilas-engine
pages:
- [index.md, Principal]
- [instalacion.md, Instalación]
- [about.md, Acerca de ...]
- [empezando.md, Empezando y los primeros pasos con pilas]
- [grupos.md, Grupos]
- [colisiones.md, Colisiones]
- [fisica.md, Fisica]

- [joystick.md, Joystick]
- [imagen.md, Imagen]
- [sonidos.md, Sonidos]
- [dibujado_simple_en_pantalla.md, Dibujado simple en pantalla]

- [interfaz.md, Interfaz de usuario]
- [desarrolladores.md, Guía para desarrolladores]
theme_dir: 'themes/custom'
