site_name: pilas-engine
pages:
- [index.md, Principal]
- [instalacion.md, Instalación]
- [about.md, Acerca de ...]
- [empezando.md, Empezando y los primeros pasos con pilas]
- [colisiones.md, Colisiones]
- [interfaz.md, Intefaz de usuario]
- [desarrolladores.md, Guía para desarrolladores]
theme_dir: 'themes/custom'
