site_name: pilas-engine
pages:
- [index.md, Principal]
- [instalacion.md, Instalación]
- [about.md, Acerca de ...]
- [empezando.md, Empezando y los primeros pasos con pilas]
- [actores.md, Actores]
- [actores_personalizados.md, Actores personalizados]
- [grupos.md, Grupos]
- [colisiones.md, Colisiones]
- [etiquetas.md, Etiquetas]
- [fisica.md, Fisica]

- [controles.md, Controles]
- [joystick.md, Joystick]
- [imagen.md, Imagen]
- [sonidos.md, Sonidos]

- [dibujado_simple_en_pantalla.md, Dibujado simple en pantalla]
- [dibujado_avanzado_con_superficies.md, Dibujado avanzado con Superficies]

- [tareas.md, Manejo de tiempo con tareas]
- [interpolacion.md, Interpolaciones]


- [controlando_la_pantalla.md, Controlando la pantalla]
- [comportamientos.md, Comportamientos]
- [escenas.md, Escenas]

- [demos.md, Demos]

- [interfaz.md, Interfaz de usuario]
- [menu.md,Como crear menúes para tu juegos]
- [mapas_y_plataformas.md, Mapas y plataformas]

- [dialogos.md, Diálogos]
- [camara.md, Manejo de Cámara]
- [eventos.md, Eventos conexiones y respuestas]
- [texto.md, Textos]
- [habilidades.md, Habilidades]
- [depurando.md, Depurando]
- [como_funciona_pilas_por_dentro.md, "¿Cómo funciona pilas por dentro?"]

- [complementos.md, Complementos]
- [desarrolladores.md, Guía para desarrolladores]

theme_dir: 'custom_theme'
theme: 'readthedocs'
